version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    container_name: giveaways_alert_proxy
    environment:
      APP_HOST: giveaways_alert_server
      APP_PORT: 4444
    networks:
      - giveaways_alert_network
    depends_on:
      - server

  server:
    image: "jermorg/giveaways-alert@sha256:0d6e57402833a9798a3a9e24d68190c6ae74d4fd8c5d936ab6ba62dc40202ada"
    container_name: giveaways_alert_server
    restart: always
    environment:
      - BotToken=TelegramBotToken 
      - Channel=@channel
      - PORT=4444
      - Url=https://www.gamerpower.com/api/filter?platform=epic-games-store.steam&type=game.loot
      - Time=300
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
    networks:
      - giveaways_alert_network

networks:
  giveaways_alert_network:
    driver: bridge