version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    container_name: spudy_app_proxy
    environment:
      APP_HOST: spudy_server
      APP_PORT: 4000
    networks:
      - spudy_network
    depends_on:
      - server

  server:
    image: "jermorg/spudy@sha256:ada6d3509c72f09ee59ce3dcdd9a8bedeb059269badf731558727b1a74befd77"
    container_name: spudy_server
    restart: always
    environment:
      - PORT=4000
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
    networks:
      - spudy_network

networks:
  spudy_network:
    driver: bridge