version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    container_name: spudy_app_proxy
    environment:
      APP_HOST: spudy_server
      APP_PORT: 4000
    networks:
      - spudy_network
    depends_on:
      - server

  server:
    image: "jermorg/spudy@sha256:78dfa86f65f99f51bc12ac37e3821709980364ec95b2cfc3262165ed64792aa3"
    container_name: spudy_server
    restart: always
    environment:
      - PORT=4000
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
    networks:
      - spudy_network

networks:
  spudy_network:
    driver: bridge