version: "3.7"

services:
  nupp-google-calendar:
    image: jermorg/nupp-google-calendar@sha256:68af5cae884509e2e42d1ac45a17db21c13aa99001a8807d0a57963f2551f212
    container_name: nupp-google-calendar
    restart: unless-stopped
    environment:
      - CALENDAR_ID=google_calendar_id
      - USER_NAME=portal_login
      - USER_PASSWORD=portal_password
      - DATE_START=2026-9-1
      - DATE_END=2026-9-30
    volumes:
      - ./data:/app/data